### ISSUE TITLE
unable to find query-string

### ISSUE THREAD

**Issue by 3boysdad** [dougmoscrop/serverless-plugin-include-dependencies#20]
so...i keep getting that it can't find, during the command "serverless package", the query-string module.  i've tried to install it globally, tried installing it locally to that project.  same error..very curious why this happens...thoughts.

**Comment by dougmoscrop** [comment]
Hey sorry my radar didn't pick this up; the short answer is you should not have this issue if the installation is "normal".  If you're `npm link` then it should not work - but should also throw a different error.

I think it's possible that if `query-string` is also in your devDependencies, it gets excluded by serverless. Can you try disabling the excludeDevDependencies feature of serverless?

Otherwise, if you can provide a minimally reproducible repo I can take a look to debug.

**Comment by dougmoscrop** [comment]
Please re-open if you are still experiencing issues, though there's been a lot of changes made to this plugin since this issue was created!
