### ISSUE TITLE
Add a cache system

### ISSUE THREAD

**Issue by n-peugnet** [dougmoscrop/serverless-plugin-include-dependencies#31]
If I understood correctly, this plugin includes dependencies by browsing recursively every file looking for require calls.

This process takes a lot of time if the dependencies tree is big and could be made a lot faster with a cache system.

For example the npm packages dependencies never changes except when the version changes so after it has been browsed once, no need to recheck it in further deployment.

**Comment by dougmoscrop** [comment]
It only parses the AST for local files, once it finds a dependency in node_modules, it switches to just pulling in dependencies noted in package.json (too many corner cases).

Since recent npm dedupes natively, I'm not sure the advantage of a cache.  I've never seen this package step take very long, but the built-in serverless one does. Make sure you set:

```yml
package:
  excludeDevDependencies: false
```

**Comment by n-peugnet** [comment]
Thank you it was as you said the built-in one that took a lot of time.

However I didn't find this information anywhere in your docs.

**Comment by dougmoscrop** [comment]
Thanks, good point! I added it to the README.
