### ISSUE TITLE
Stop excluding aws-sdk

### ISSUE THREAD

**Issue by dougmoscrop** [dougmoscrop/serverless-plugin-include-dependencies#36]
AWS no longer suggests using the Lambda-provided bundled SDK, everyone should ship their own. This is especially true for v3, but even v2 has had some transitive dependency changes that cause unexpected problems

**Comment by sjl2** [comment]
I would like to second this. To add some additional color, with the latest OS upgrade, AWS updated the default `aws-sdk` version past v2.304.0 which broke our service because of how we were [promisifying it with Bluebird](https://github.com/aws/aws-sdk-js/issues/2229). 

In the process of debugging, we were stumped as to why we were unable to include `aws-sdk`. Having found that it was ignored, we had to resolve to updating our code which was not the fastest approach.

We really like the plugin, but we need to start including `aws-sdk` to avoid downtime in the future. We'll have to move off it without  changing it to allow us to package `aws-sdk` OR allowing the plugin to be configured to not ignore it (since we appreciate that it's a breaking change). 

Is there another work-around we're not considering?

**Comment by dougmoscrop** [comment]
No, there's no reason not to exclude it, it just will make packages larger and possibly prevent console debugging - not that I use those


This isn't high on my priority list however, so it's more likely to ship from a PR
