### ISSUE TITLE
Is this package already inside serverless?

### ISSUE THREAD

**Issue by richardtapendium** [dougmoscrop/serverless-plugin-include-dependencies#52]
Based on serverless docs [here](https://www.serverless.com/framework/docs/providers/aws/guide/packaging#exclude--include), it looks like this functionality is already in the serverless core.

If so, should we update the README to reflect this so people don't unnecessarily install this plugin?

**Comment by dougmoscrop** [comment]
No, the serverless core functionality merely excludes dev dependencies and lets you hand-code a list of patterns to include/exclude, rather than excluding all dependencies by default and only adding in the ones that are required() from your handlers or are transitive dependencies of those.

The built-in functionality is also slower, so installing this plugin, plus `serverless-plugin-common-excludes`, and setting `excludeDevDependencies: false` results in a faster package step with a smaller output.
